name: Build of the container
on:
  push:
    branches:
      - maven
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 0.0
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build and test with Maven
        run: |
            mvn clean install
    
  compose:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Determine Version
        id: determine-version
        run: |
          echo "VERSION=$((GITHUB_RUN_NUMBER))"
          echo "::set-output name=version::${VERSION}"

      - name: Modify Docker Compose YAML
        run: |
          sed -i "s/{{ TAG }}/${{ steps.determine-version.outputs.version }}/g" docker-compose.yml

      - name: Start Docker Compose
        run: docker-compose up -d

    - name: Clean Up
      run: docker-compose down --volumes