# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - ClinicaMascotasPyC

on:
  push:
    branches:
      - maven
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build and test with Maven
        run: |
            mvn clean install
            mvn jacoco:report

      - name: Display the contents of jacoco.xml
        run: cat target/site/jacoco/jacoco.xml
        
      - name: Check Code Coverage
        run: |
          coverage=$(grep -Po '<counter type="LINE" missed="[0-9]+" covered="[0-9]+">' target/site/jacoco/jacoco.xml | grep -oP 'covered="\K[0-9]+')
          echo "Coverage value is: $coverage"
          if [ "$coverage" -lt "30" ]; then
            echo "Code coverage is below the threshold. Coverage: $coverage%"
            exit 1
          fi
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ClinicaMascotasPyC'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_96E8A9E88945452EBC2D549CAAC2422D }}
          package: '*.jar'
